INSERT INTO COLLEGE(NAME) VALUES('MUM-COLLEGE OF COMPUTER SCIENCE');
INSERT INTO COLLEGE(NAME) VALUES('GEORGIA TECH');

INSERT INTO ADDRESS(CITY,STREET,ZIP_CODE)VALUES('ROSWELL','ASHLEIGH LANE',30004);
INSERT INTO ADDRESS(CITY,STREET,ZIP_CODE)VALUES('IRVING','BLOCK DRIVE',75038);

INSERT INTO STATE(COUNTRY,NAME,STATE_CODE) VALUES('USA','TEXAS','TX');
INSERT INTO STATE(COUNTRY,NAME,STATE_CODE) VALUES('USA','GEORGIA','GA');

INSERT INTO DEPARTMENT(DEPARTMENT_CODE,NAME)VALUES('IT001','INFORMATION TECHNOLOGY');
INSERT INTO DEPARTMENT(DEPARTMENT_CODE,NAME)VALUES('CSE002','COMPUTER SCIENCE');

INSERT INTO STUDENT(AGE,FIRST_NAME,LAST_NAME)VALUES(32,'AMANUEL','GEBRU');
INSERT INTO STUDENT(AGE,FIRST_NAME,LAST_NAME)VALUES(24,'HAGOS','KIDANE');

COMMIT;